# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Always restore open sites when qutebrowser is reopened.
# Type: Bool
c.auto_save.session = True

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = 'www.google.ch'

# Search engines which can be used via the address bar. Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` signs. The search engine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {'DEFAULT': 'https://www.google.ch/search?hl=fr&q={}'}

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = 'https://www.google.ch'

# Bindings for normal mode
config.bind(',m', 'spawn /usr/bin/optirun /usr/bin/mpv --cache=4000 --force-window=immediate {url} --keep-open')
config.bind('<ctrl+left>', 'tab-prev')
config.bind('<ctrl+leftarrow>', 'tab-prev')
config.bind('<ctrl+p>', 'spawn --userscript qute-pass')
config.bind('<ctrl+right>', 'tab-next')
config.bind('Backspace', 'H')
config.bind('H', 'back')
config.bind('backspace', 'back')
